### ISSUE TITLE
Setting image programmatically with a URLRequest

### ISSUE THREAD

**Issue by surayashivji** [gkye/ComplimentaryGradientView#10]
Are images able to be set without specifying the image name in the Storyboard? For some reason, when I set the image programmatically, to either an image in the project or one downloaded from the web, it doesn't work unless I specify it in the storyboard as well. 

```
@IBOutlet weak var gradientBG: ComplimentaryGradientView!

let bg : UIImage = largeImage
self.gradientBG.image = UIImage(named: "test.png")
self.gradientBG.gradientTpye = .backgroundPrimary
self.gradientBG.gradientStartPoint = .left
```

This works when I set the following in Storyboard:
<img width="290" alt="screen shot 2016-10-10 at 4 12 29 pm" src="https://cloud.githubusercontent.com/assets/12003060/19254043/82cb63d2-8f04-11e6-9e38-c148c10252a8.png">

However, because I want to generate a gradient from an image downloaded from the web, I cannot set it's filename in Storyboard. 

Is there something I'm missing to be able to set a gradient on an image without specifying it's name in Storyboard?

Thank you for the fantastic project!

**Comment by gkye** [comment]
Programtically setting the image should work, I'll look into this later today

**Comment by gkye** [comment]
hmm strange just tested this out and everything works as it should. Could you please attach a demo project to help me better understand what exactly is going on?

**Comment by surayashivji** [comment]
Hm that's strange. Yep! Attached is a demo project. In MoviesDetailViewController.swift I have a variable called gradientBG which is an IBOutlet to the ComplimentaryGradientView in the Storyboard. In the setupUI() method I set the image for the gradientBG to the image received from the AFNetworking method, setImageWith, which sets a UIImage based on a request. 

[Flix.zip](https://github.com/gkye/ComplimentaryGradientView/files/520895/Flix.zip)

It runs Swift 3 & Xcode 8-- let me know if you need any more clarification on the demo.

**Comment by surayashivji** [comment]
I was able to get it working for an image I have saved in my project but not for one being downloaded from the web

**Comment by gkye** [comment]
Figured out the problem. The gradient layer wasn't being added when the image is set, I've fixed it and will update the pod soon. just `pod update`.
Btw noticed you're using the moviedb api, I've created a wrapper for it in swift here https://github.com/gkye/TheMovieDatabaseSwiftWrapper

**Comment by surayashivji** [comment]
Great! Thanks-- I'll run `pod update`. Oh what a coincidence-- cool wrapper I'll check it out.

**Comment by surayashivji** [comment]
Do you have a demo of this working? The image still isn't being set when I run it with the update

**Comment by gkye** [comment]
hmm, strange i tested it on the project you attached it worked fine. see the attached folder 
[Flix.zip](https://github.com/gkye/ComplimentaryGradientView/files/528708/Flix.zip)
